version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sourav
      - POSTGRES_DB=grocery_booking_app_db
    volumes:
      - postgres-data:/var/lib/postgressql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:
# version: "3.8"

# services:
#   ts-node-docker:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: base
#     volumes:
#       - ./src:/home/node/app/src
#       - ./nodemon.json:/home/node/app/nodemon.json
#     container_name: ts-node-docker
#     expose:
#       - "4000"
#     ports:
#       - "4000:4000"
#     command: npm run start
